version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase
    networks:
      - my-app-network

networks:
  my-app-network:
    external: true  # Utiliser un réseau existant
